// <auto-generated />
using System;
using BancoHistorico;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BancoHistorico.Migrations
{
    [DbContext(typeof(CadastroContext))]
    [Migration("20230113182913_ini")]
    partial class ini
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BancoHistorico.Cadastros.Domain.Coluna", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColumnNameOf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroColuna")
                        .HasColumnType("int");

                    b.Property<string>("OwnsOne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TabelaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("max_length")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TabelaId");

                    b.ToTable("Colunas");
                });

            modelBuilder.Entity("BancoHistorico.Cadastros.Domain.Constraint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ColunaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("definition")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("definition");

                    b.HasKey("Id");

                    b.HasIndex("ColunaId");

                    b.ToTable("Restricoes");
                });

            modelBuilder.Entity("BancoHistorico.Cadastros.Domain.Fk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ColunaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FK_CONSTRAINT")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FK_CONSTRAINT");

                    b.Property<string>("parent_column")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("parent_column");

                    b.Property<string>("parent_object")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("parent_object");

                    b.Property<string>("referenced_column")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("referenced_column");

                    b.Property<int>("referenced_column_id")
                        .HasColumnType("int")
                        .HasColumnName("referenced_column_id");

                    b.Property<string>("referenced_object")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("referenced_object");

                    b.Property<int>("referenced_object_id")
                        .HasColumnType("int")
                        .HasColumnName("referenced_object_id");

                    b.HasKey("Id");

                    b.HasIndex("ColunaId");

                    b.ToTable("Fk");
                });

            modelBuilder.Entity("BancoHistorico.Cadastros.Domain.Indice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ColunaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KeyNameOf")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("KeyNameOf");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<Guid?>("TabelaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("filter_definition")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("filter_definition");

                    b.Property<bool>("is_primary_key")
                        .HasColumnType("bit")
                        .HasColumnName("is_primary_key");

                    b.Property<bool>("is_unique")
                        .HasColumnType("bit")
                        .HasColumnName("is_unique");

                    b.HasKey("Id");

                    b.HasIndex("ColunaId");

                    b.HasIndex("TabelaId");

                    b.ToTable("Indices");
                });

            modelBuilder.Entity("BancoHistorico.Cadastros.Domain.Projeto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SolucaoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SolucaoId");

                    b.ToTable("Projetos");
                });

            modelBuilder.Entity("BancoHistorico.Cadastros.Domain.Solucao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Solucao");
                });

            modelBuilder.Entity("BancoHistorico.Cadastros.Domain.Tabela", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<int>("NumeroTabela")
                        .HasColumnType("int")
                        .HasColumnName("Contador");

                    b.Property<Guid>("ProjetoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("area")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("area");

                    b.Property<string>("tableNameOf")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tableNameOf");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.ToTable("Tabelas");
                });

            modelBuilder.Entity("BancoHistorico.Cadastros.Domain.Coluna", b =>
                {
                    b.HasOne("BancoHistorico.Cadastros.Domain.Tabela", "Tabela")
                        .WithMany("ColunaItems")
                        .HasForeignKey("TabelaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tabela");
                });

            modelBuilder.Entity("BancoHistorico.Cadastros.Domain.Constraint", b =>
                {
                    b.HasOne("BancoHistorico.Cadastros.Domain.Coluna", null)
                        .WithMany("constraints")
                        .HasForeignKey("ColunaId");
                });

            modelBuilder.Entity("BancoHistorico.Cadastros.Domain.Fk", b =>
                {
                    b.HasOne("BancoHistorico.Cadastros.Domain.Coluna", null)
                        .WithMany("fks")
                        .HasForeignKey("ColunaId");
                });

            modelBuilder.Entity("BancoHistorico.Cadastros.Domain.Indice", b =>
                {
                    b.HasOne("BancoHistorico.Cadastros.Domain.Coluna", null)
                        .WithMany("IndiceItems")
                        .HasForeignKey("ColunaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BancoHistorico.Cadastros.Domain.Tabela", null)
                        .WithMany("IndiceItems")
                        .HasForeignKey("TabelaId");
                });

            modelBuilder.Entity("BancoHistorico.Cadastros.Domain.Projeto", b =>
                {
                    b.HasOne("BancoHistorico.Cadastros.Domain.Solucao", "Solucao")
                        .WithMany("ProjetoItems")
                        .HasForeignKey("SolucaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solucao");
                });

            modelBuilder.Entity("BancoHistorico.Cadastros.Domain.Tabela", b =>
                {
                    b.HasOne("BancoHistorico.Cadastros.Domain.Projeto", "Projeto")
                        .WithMany("TabelaItems")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("BancoHistorico.Cadastros.Domain.Coluna", b =>
                {
                    b.Navigation("constraints");

                    b.Navigation("fks");

                    b.Navigation("IndiceItems");
                });

            modelBuilder.Entity("BancoHistorico.Cadastros.Domain.Projeto", b =>
                {
                    b.Navigation("TabelaItems");
                });

            modelBuilder.Entity("BancoHistorico.Cadastros.Domain.Solucao", b =>
                {
                    b.Navigation("ProjetoItems");
                });

            modelBuilder.Entity("BancoHistorico.Cadastros.Domain.Tabela", b =>
                {
                    b.Navigation("ColunaItems");

                    b.Navigation("IndiceItems");
                });
#pragma warning restore 612, 618
        }
    }
}
